Update assignment_4.py
added the anomaly detection transformer
attempted to test on the unseen data and got this error:

/deac/csc/classes/csc373/kamplm24/assignment_4/assignment_4.py:191: DtypeWarning: Columns (228,229,274,277,294,347,348,393,396,413,587) have mixed types. Specify dtype option on import or set low_memory=False.
  new_data = pd.read_csv(new_molecules_path)
Traceback (most recent call last):
  File "/deac/csc/classes/csc373/kamplm24/assignment_4/assignment_4.py", line 208, in <module>
    test_on_unseen_data()
  File "/deac/csc/classes/csc373/kamplm24/assignment_4/assignment_4.py", line 195, in test_on_unseen_data
    predictions = model.predict(new_features)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deac/csc/classes/csc373/software/csc373/lib/python3.11/site-packages/sklearn/pipeline.py", line 787, in predict
    Xt = transform.transform(Xt)
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/deac/csc/classes/csc373/software/csc373/lib/python3.11/site-packages/sklearn/pipeline.py", line 1092, in transform
    Xt = transform.transform(Xt, **routed_params[name].transform)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deac/csc/classes/csc373/software/csc373/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 319, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deac/csc/classes/csc373/kamplm24/assignment_4/assignment_4.py", line 67, in transform
    anomaly_scores = self.iforest.decision_function(X)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/deac/csc/classes/csc373/software/csc373/lib/python3.11/site-packages/sklearn/ensemble/_iforest.py", line 474, in decision_function
    return self.score_samples(X) - self.offset_
           ^^^^^^^^^^^^^^^^^^^^^
  File "/deac/csc/classes/csc373/software/csc373/lib/python3.11/site-packages/sklearn/ensemble/_iforest.py", line 519, in score_samples
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/deac/csc/classes/csc373/software/csc373/lib/python3.11/site-packages/sklearn/utils/validation.py", line 2919, in validate_data
    _check_feature_names(_estimator, X, reset=reset)
  File "/deac/csc/classes/csc373/software/csc373/lib/python3.11/site-packages/sklearn/utils/validation.py", line 2777, in _check_feature_names
    raise ValueError(message)
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- CID